import type { ControlsState } from "@/components/ControlsPanel";
import type { TournamentRow } from "./sim/types";
import type { DictKey } from "./i18n/dict";

export interface DemoScenario {
  id: string;
  labelKey: DictKey;
  description: string;
  schedule: TournamentRow[];
  controls: ControlsState;
  icon?: string;
  disabled?: boolean;
}

const BASE_CONTROLS: ControlsState = {
  scheduleRepeats: 200,
  samples: 10_000,
  bankroll: 0,
  seed: 42,
  finishModelId: "power-law",
  alphaOverride: null,
  compareWithPrimedope: true,
  compareMode: "primedope",
  roiStdErr: 0,
  roiShockPerTourney: 0,
  roiShockPerSession: 0,
  roiDriftSigma: 0,
  tiltFastGain: 0,
  tiltFastScale: 0,
  tiltSlowGain: 0,
  tiltSlowThreshold: 0,
  tiltSlowMinDuration: 500,
  tiltSlowRecoveryFrac: 0.5,
  modelPresetId: "naive",
};

export const SCENARIOS: DemoScenario[] = [
  {
    id: "primedope-reference",
    labelKey: "demo.primedopeReference",
    description:
      "Сверка с PrimeDope: 100 игроков, 15 мест, $50+$5.50, ROI 10%, 1000 турниров. Минимальный набор — удобно положить рядом наш результат и PrimeDope'овский.",
    schedule: [
      {
        id: "pd-1",
        label: "$50 MTT (PrimeDope reference)",
        players: 100,
        buyIn: 50,
        rake: 0.11,
        roi: 0.1,
        payoutStructure: "mtt-standard",
        count: 1000,
      },
    ],
    controls: {
      ...BASE_CONTROLS,
      scheduleRepeats: 1,
      samples: 1000,
      bankroll: 1000,
      compareWithPrimedope: true,
      compareMode: "primedope",
    },
  },
  {
    id: "micro-grinder",
    labelKey: "demo.microGrinder",
    disabled: true,
    description:
      "$1–$22 daily staples: GG Bounty Hunters $1/$5, PS Bounty Builder $11, PS Big $11, Global MILLION$.",
    schedule: [
      {
        id: "micro-1",
        label: "GG Bounty Hunters $1.05",
        players: 5500,
        buyIn: 1,
        rake: 0.05,
        roi: 0.18,
        payoutStructure: "mtt-gg-bounty",
        bountyFraction: 0.5,
        progressiveKO: true,
        guarantee: 5000,
        count: 8,
      },
      {
        id: "micro-2",
        label: "GG Bounty Hunters $5.25",
        players: 3500,
        buyIn: 5,
        rake: 0.05,
        roi: 0.15,
        payoutStructure: "mtt-gg-bounty",
        bountyFraction: 0.5,
        progressiveKO: true,
        guarantee: 15_000,
        count: 10,
      },
      {
        id: "micro-3",
        label: "PS Big $11",
        players: 3000,
        buyIn: 10,
        rake: 0.09,
        roi: 0.12,
        payoutStructure: "mtt-pokerstars",
        guarantee: 25_000,
        count: 8,
      },
      {
        id: "micro-4",
        label: "PS Bounty Builder $11",
        players: 2000,
        buyIn: 10,
        rake: 0.09,
        roi: 0.12,
        payoutStructure: "mtt-top-heavy",
        bountyFraction: 0.5,
        progressiveKO: true,
        guarantee: 20_000,
        count: 6,
      },
      {
        id: "micro-5",
        label: "GG Global MILLION$ $10.50",
        players: 10_000,
        buyIn: 10,
        rake: 0.05,
        roi: 0.1,
        payoutStructure: "mtt-pokerstars",
        guarantee: 100_000,
        count: 2,
      },
    ],
    controls: {
      ...BASE_CONTROLS,
      scheduleRepeats: 250,
      bankroll: 300,
    },
  },
  {
    id: "mid-grinder",
    labelKey: "demo.midGrinder",
    disabled: true,
    description:
      "Mid-stakes: PS Big $55, GG Bounty Hunters HR $55/$105, GG Masters $150, Thursday Thrill.",
    schedule: [
      {
        id: "mid-1",
        label: "PS Big $55",
        players: 1800,
        buyIn: 50,
        rake: 0.09,
        roi: 0.12,
        payoutStructure: "mtt-pokerstars",
        guarantee: 75_000,
        count: 18,
      },
      {
        id: "mid-2",
        label: "GG Bounty Hunters HR $55",
        players: 3500,
        buyIn: 50,
        rake: 0.1,
        roi: 0.11,
        payoutStructure: "mtt-gg-bounty",
        bountyFraction: 0.5,
        progressiveKO: true,
        guarantee: 75_000,
        count: 10,
      },
      {
        id: "mid-3",
        label: "PS Thursday Thrill $109",
        players: 1500,
        buyIn: 100,
        rake: 0.09,
        roi: 0.09,
        payoutStructure: "mtt-pokerstars",
        guarantee: 150_000,
        count: 6,
      },
      {
        id: "mid-4",
        label: "GG Masters $150",
        players: 1200,
        buyIn: 135,
        rake: 15 / 135,
        roi: 0.07,
        payoutStructure: "mtt-top-heavy",
        guarantee: 150_000,
        count: 4,
      },
    ],
    controls: {
      ...BASE_CONTROLS,
      scheduleRepeats: 200,
      bankroll: 5000,
      finishModelId: "stretched-exp",
    },
  },
  {
    id: "hyper-night",
    labelKey: "demo.hyperNight",
    disabled: true,
    description: "Hyper-turbo SNG + HU night — high-variance short stuff",
    schedule: [
      {
        id: "hyper-1",
        label: "$10 hyper 6-max",
        players: 6,
        buyIn: 10,
        rake: 0.05,
        roi: 0.06,
        payoutStructure: "sng-65-35",
        count: 30,
      },
      {
        id: "hyper-2",
        label: "$25 HU",
        players: 2,
        buyIn: 25,
        rake: 0.04,
        roi: 0.04,
        payoutStructure: "winner-takes-all",
        count: 15,
      },
    ],
    controls: {
      ...BASE_CONTROLS,
      scheduleRepeats: 100,
      bankroll: 500,
      finishModelId: "linear-skill",
    },
  },
  {
    id: "morning-night-reg",
    labelKey: "demo.morningNightReg",
    disabled: true,
    description:
      "Утренний + ночной рег: мягкие утренние евро-филды и жирный ночной прайм-тайм на GG и PS.",
    schedule: [
      {
        id: "mnr-1",
        label: "GG Bounty Hunters $5.25 (morning)",
        players: 2500,
        buyIn: 5,
        rake: 0.05,
        roi: 0.16,
        payoutStructure: "mtt-gg-bounty",
        bountyFraction: 0.5,
        progressiveKO: true,
        guarantee: 10_000,
        count: 8,
      },
      {
        id: "mnr-2",
        label: "PS Big $11 (morning)",
        players: 2200,
        buyIn: 10,
        rake: 0.09,
        roi: 0.13,
        payoutStructure: "mtt-pokerstars",
        guarantee: 20_000,
        count: 6,
      },
      {
        id: "mnr-3",
        label: "PS Big $22 (prime)",
        players: 3500,
        buyIn: 20,
        rake: 0.09,
        roi: 0.1,
        payoutStructure: "mtt-pokerstars",
        guarantee: 50_000,
        count: 10,
      },
      {
        id: "mnr-4",
        label: "GG Bounty Hunters $25 (prime)",
        players: 3000,
        buyIn: 22,
        rake: 3 / 22,
        roi: 0.09,
        payoutStructure: "mtt-gg-bounty",
        bountyFraction: 0.5,
        progressiveKO: true,
        guarantee: 60_000,
        count: 10,
      },
      {
        id: "mnr-5",
        label: "PS Bounty Builder $22 (prime)",
        players: 2000,
        buyIn: 20,
        rake: 0.09,
        roi: 0.09,
        payoutStructure: "mtt-top-heavy",
        bountyFraction: 0.5,
        progressiveKO: true,
        guarantee: 40_000,
        count: 6,
      },
      {
        id: "mnr-6",
        label: "GG Global MILLION$ $10.50",
        players: 10_000,
        buyIn: 10,
        rake: 0.05,
        roi: 0.1,
        payoutStructure: "mtt-pokerstars",
        guarantee: 100_000,
        count: 2,
      },
    ],
    controls: {
      ...BASE_CONTROLS,
      scheduleRepeats: 220,
      samples: 12_000,
      bankroll: 1500,
      finishModelId: "stretched-exp",
      compareWithPrimedope: true,
    },
  },
  {
    id: "satellite-feeder",
    labelKey: "demo.satelliteFeeder",
    disabled: true,
    description:
      "Satellite-heavy qualifier chain: cheap feeders into a target tourney. Field sizes vary wildly — PrimeDope can't model this.",
    schedule: [
      {
        id: "sat-1",
        label: "$2 sat to $22",
        players: 100,
        buyIn: 2,
        rake: 0.1,
        roi: 0.2,
        payoutStructure: "sng-50-30-20",
        count: 15,
        fieldVariability: { kind: "uniform", min: 20, max: 250, buckets: 6 },
      },
      {
        id: "sat-2",
        label: "$11 sat to $109",
        players: 200,
        buyIn: 10,
        rake: 0.08,
        roi: 0.18,
        payoutStructure: "mtt-flat",
        count: 8,
        fieldVariability: { kind: "uniform", min: 60, max: 450, buckets: 6 },
      },
      {
        id: "sat-3",
        label: "$109 target MTT",
        players: 1500,
        buyIn: 100,
        rake: 0.08,
        roi: 0.15,
        payoutStructure: "mtt-pokerstars",
        guarantee: 200_000,
        count: 1,
      },
    ],
    controls: {
      ...BASE_CONTROLS,
      scheduleRepeats: 100,
      samples: 10_000,
      bankroll: 1500,
      finishModelId: "power-law",
      compareWithPrimedope: true,
    },
  },
  {
    id: "romeo-pro",
    labelKey: "demo.romeoPro",
    icon: "/scenarios/romeo.png",
    description:
      "RomeoPro mode — ~250 турниров за сессию, 60% ноки / 40% фризы, у каждого турика отдельными слотами стоят лейт-ре-реги с пониженным ROI.",
    schedule: [
      // ---- PKO generics (60% of load, ~148 tourneys) ----
      {
        id: "romeo-pko25-1",
        label: "GG PKO $25 (1st)",
        players: 2500,
        buyIn: 22,
        rake: 3 / 22,
        roi: 0.12,
        payoutStructure: "mtt-gg-bounty",
        bountyFraction: 0.5,
        progressiveKO: true,
        guarantee: 50_000,
        count: 40,
      },
      {
        id: "romeo-pko25-2",
        label: "GG PKO $25 (re-1)",
        players: 2500,
        buyIn: 22,
        rake: 3 / 22,
        roi: 0.06,
        payoutStructure: "mtt-gg-bounty",
        bountyFraction: 0.5,
        progressiveKO: true,
        guarantee: 50_000,
        count: 20,
      },
      {
        id: "romeo-pko25-3",
        label: "GG PKO $25 (re-2)",
        players: 2500,
        buyIn: 22,
        rake: 3 / 22,
        roi: 0.03,
        payoutStructure: "mtt-gg-bounty",
        bountyFraction: 0.5,
        progressiveKO: true,
        guarantee: 50_000,
        count: 10,
      },
      {
        id: "romeo-pko55-1",
        label: "GG PKO $55 (1st)",
        players: 2000,
        buyIn: 50,
        rake: 0.1,
        roi: 0.09,
        payoutStructure: "mtt-gg-bounty",
        bountyFraction: 0.5,
        progressiveKO: true,
        guarantee: 100_000,
        count: 25,
      },
      {
        id: "romeo-pko55-2",
        label: "GG PKO $55 (re-1)",
        players: 2000,
        buyIn: 50,
        rake: 0.1,
        roi: 0.045,
        payoutStructure: "mtt-gg-bounty",
        bountyFraction: 0.5,
        progressiveKO: true,
        guarantee: 100_000,
        count: 12,
      },
      {
        id: "romeo-pko55-3",
        label: "GG PKO $55 (re-2)",
        players: 2000,
        buyIn: 50,
        rake: 0.1,
        roi: 0.0225,
        payoutStructure: "mtt-gg-bounty",
        bountyFraction: 0.5,
        progressiveKO: true,
        guarantee: 100_000,
        count: 6,
      },
      {
        id: "romeo-pko22ps-1",
        label: "PS BB $22 (1st)",
        players: 1800,
        buyIn: 20,
        rake: 0.09,
        roi: 0.1,
        payoutStructure: "mtt-top-heavy",
        bountyFraction: 0.5,
        progressiveKO: true,
        guarantee: 40_000,
        count: 20,
      },
      {
        id: "romeo-pko22ps-2",
        label: "PS BB $22 (re-1)",
        players: 1800,
        buyIn: 20,
        rake: 0.09,
        roi: 0.05,
        payoutStructure: "mtt-top-heavy",
        bountyFraction: 0.5,
        progressiveKO: true,
        guarantee: 40_000,
        count: 10,
      },
      {
        id: "romeo-pko22ps-3",
        label: "PS BB $22 (re-2)",
        players: 1800,
        buyIn: 20,
        rake: 0.09,
        roi: 0.025,
        payoutStructure: "mtt-top-heavy",
        bountyFraction: 0.5,
        progressiveKO: true,
        guarantee: 40_000,
        count: 5,
      },
      // ---- Freezeout generics (40% of load, ~104 tourneys) ----
      {
        id: "romeo-fr22-1",
        label: "GG $22 freeze (1st)",
        players: 1500,
        buyIn: 20,
        rake: 0.1,
        roi: 0.1,
        payoutStructure: "mtt-gg",
        guarantee: 25_000,
        count: 30,
      },
      {
        id: "romeo-fr22-2",
        label: "GG $22 freeze (re-1)",
        players: 1500,
        buyIn: 20,
        rake: 0.1,
        roi: 0.05,
        payoutStructure: "mtt-gg",
        guarantee: 25_000,
        count: 15,
      },
      {
        id: "romeo-fr22-3",
        label: "GG $22 freeze (re-2)",
        players: 1500,
        buyIn: 20,
        rake: 0.1,
        roi: 0.025,
        payoutStructure: "mtt-gg",
        guarantee: 25_000,
        count: 7,
      },
      {
        id: "romeo-fr55-1",
        label: "PS Big $55 (1st)",
        players: 1800,
        buyIn: 50,
        rake: 0.09,
        roi: 0.08,
        payoutStructure: "mtt-pokerstars",
        guarantee: 75_000,
        count: 30,
      },
      {
        id: "romeo-fr55-2",
        label: "PS Big $55 (re-1)",
        players: 1800,
        buyIn: 50,
        rake: 0.09,
        roi: 0.04,
        payoutStructure: "mtt-pokerstars",
        guarantee: 75_000,
        count: 15,
      },
      {
        id: "romeo-fr55-3",
        label: "PS Big $55 (re-2)",
        players: 1800,
        buyIn: 50,
        rake: 0.09,
        roi: 0.02,
        payoutStructure: "mtt-pokerstars",
        guarantee: 75_000,
        count: 7,
      },
      // ---- Named events, 1 shot each ----
      {
        id: "romeo-named-thrill",
        label: "PS Thursday Thrill $109",
        players: 1500,
        buyIn: 100,
        rake: 0.09,
        roi: 0.07,
        payoutStructure: "mtt-pokerstars",
        guarantee: 150_000,
        count: 1,
      },
      {
        id: "romeo-named-bhmain",
        label: "GG BH Main $210",
        players: 2000,
        buyIn: 200,
        rake: 0.05,
        roi: 0.05,
        payoutStructure: "mtt-gg-bounty",
        bountyFraction: 0.5,
        progressiveKO: true,
        guarantee: 400_000,
        count: 1,
      },
    ],
    controls: {
      ...BASE_CONTROLS,
      scheduleRepeats: 50,
      samples: 8_000,
      bankroll: 15_000,
      finishModelId: "power-law",
    },
  },
  {
    id: "sunday-majors",
    labelKey: "demo.sundayMajors",
    icon: "/scenarios/sunday.svg",
    disabled: true,
    description:
      "Sunday schedule: PS Sunday Million, GG Bounty Hunters HR Main, PS Bounty Builder HR.",
    schedule: [
      {
        id: "sun-1",
        label: "PS Sunday Million",
        players: 6000,
        buyIn: 100,
        rake: 0.09,
        roi: 0.2,
        payoutStructure: "mtt-sunday-million",
        guarantee: 1_000_000,
        count: 1,
      },
      {
        id: "sun-2",
        label: "GG Bounty Hunters HR $210",
        players: 2500,
        buyIn: 200,
        rake: 0.05,
        roi: 0.18,
        payoutStructure: "mtt-gg-bounty",
        bountyFraction: 0.5,
        progressiveKO: true,
        guarantee: 500_000,
        count: 1,
      },
      {
        id: "sun-3",
        label: "PS Bounty Builder HR $109",
        players: 2000,
        buyIn: 100,
        rake: 0.09,
        roi: 0.18,
        payoutStructure: "mtt-top-heavy",
        bountyFraction: 0.5,
        progressiveKO: true,
        guarantee: 200_000,
        count: 1,
      },
    ],
    controls: {
      ...BASE_CONTROLS,
      scheduleRepeats: 52,
      samples: 15_000,
      bankroll: 20_000,
      finishModelId: "stretched-exp",
    },
  },
];

export function findScenario(id: string): DemoScenario | undefined {
  return SCENARIOS.find((s) => s.id === id);
}
