import type { ControlsState } from "@/components/ControlsPanel";
import type { TournamentRow } from "./sim/types";
import type { DictKey } from "./i18n/dict";

export interface DemoScenario {
  id: string;
  labelKey: DictKey;
  description: string;
  schedule: TournamentRow[];
  controls: ControlsState;
  icon?: string;
}

const BASE_CONTROLS: ControlsState = {
  scheduleRepeats: 200,
  samples: 10_000,
  bankroll: 0,
  seed: 42,
  finishModelId: "power-law",
  alphaOverride: null,
  compareWithPrimedope: true,
  compareMode: "primedope",
  primedopeStyleEV: true,
  roiStdErr: 0,
  roiShockPerTourney: 0,
  roiShockPerSession: 0,
  roiDriftSigma: 0,
  tiltFastGain: 0,
  tiltFastScale: 0,
  tiltSlowGain: 0,
  tiltSlowThreshold: 0,
  tiltSlowMinDuration: 500,
  tiltSlowRecoveryFrac: 0.5,
  modelPresetId: "naive",
};

export const SCENARIOS: DemoScenario[] = [
  {
    id: "primedope-reference",
    labelKey: "demo.primedopeReference",
    description:
      "Сверка с PrimeDope: 100 игроков, 15 мест, $50+$5.50, ROI 10%, 1000 турниров. Минимальный набор — удобно положить рядом наш результат и PrimeDope'овский.",
    schedule: [
      {
        id: "pd-1",
        label: "$50 MTT (PrimeDope reference)",
        players: 100,
        buyIn: 50,
        rake: 0.11,
        roi: 0.1,
        payoutStructure: "mtt-standard",
        count: 1000,
      },
    ],
    controls: {
      ...BASE_CONTROLS,
      scheduleRepeats: 1,
      samples: 1000,
      bankroll: 1000,
      compareWithPrimedope: true,
      compareMode: "primedope",
    },
  },
  {
    id: "romeo-pro",
    labelKey: "demo.romeoPro",
    icon: "/scenarios/romeo.png",
    description:
      "RomeoPro mode — ~250 турниров за сессию, 60% ноки / 40% фризы, у каждого турика отдельными слотами стоят лейт-ре-реги с пониженным ROI.",
    schedule: [
      // ---- PKO generics (60% of load, ~148 tourneys) ----
      {
        id: "romeo-pko25-1",
        label: "GG PKO $25 (1st)",
        players: 2500,
        buyIn: 22,
        rake: 3 / 22,
        roi: 0.12,
        payoutStructure: "mtt-gg-bounty",
        bountyFraction: 0.5,
        guarantee: 50_000,
        count: 40,
      },
      {
        id: "romeo-pko25-2",
        label: "GG PKO $25 (re-1)",
        players: 2500,
        buyIn: 22,
        rake: 3 / 22,
        roi: 0.06,
        payoutStructure: "mtt-gg-bounty",
        bountyFraction: 0.5,
        guarantee: 50_000,
        count: 20,
      },
      {
        id: "romeo-pko25-3",
        label: "GG PKO $25 (re-2)",
        players: 2500,
        buyIn: 22,
        rake: 3 / 22,
        roi: 0.03,
        payoutStructure: "mtt-gg-bounty",
        bountyFraction: 0.5,
        guarantee: 50_000,
        count: 10,
      },
      {
        id: "romeo-pko55-1",
        label: "GG PKO $55 (1st)",
        players: 2000,
        buyIn: 50,
        rake: 0.1,
        roi: 0.09,
        payoutStructure: "mtt-gg-bounty",
        bountyFraction: 0.5,
        guarantee: 100_000,
        count: 25,
      },
      {
        id: "romeo-pko55-2",
        label: "GG PKO $55 (re-1)",
        players: 2000,
        buyIn: 50,
        rake: 0.1,
        roi: 0.045,
        payoutStructure: "mtt-gg-bounty",
        bountyFraction: 0.5,
        guarantee: 100_000,
        count: 12,
      },
      {
        id: "romeo-pko55-3",
        label: "GG PKO $55 (re-2)",
        players: 2000,
        buyIn: 50,
        rake: 0.1,
        roi: 0.0225,
        payoutStructure: "mtt-gg-bounty",
        bountyFraction: 0.5,
        guarantee: 100_000,
        count: 6,
      },
      {
        id: "romeo-pko22ps-1",
        label: "PS BB $22 (1st)",
        players: 1800,
        buyIn: 20,
        rake: 0.09,
        roi: 0.1,
        payoutStructure: "mtt-top-heavy",
        bountyFraction: 0.5,
        guarantee: 40_000,
        count: 20,
      },
      {
        id: "romeo-pko22ps-2",
        label: "PS BB $22 (re-1)",
        players: 1800,
        buyIn: 20,
        rake: 0.09,
        roi: 0.05,
        payoutStructure: "mtt-top-heavy",
        bountyFraction: 0.5,
        guarantee: 40_000,
        count: 10,
      },
      {
        id: "romeo-pko22ps-3",
        label: "PS BB $22 (re-2)",
        players: 1800,
        buyIn: 20,
        rake: 0.09,
        roi: 0.025,
        payoutStructure: "mtt-top-heavy",
        bountyFraction: 0.5,
        guarantee: 40_000,
        count: 5,
      },
      // ---- Freezeout generics (40% of load, ~104 tourneys) ----
      {
        id: "romeo-fr22-1",
        label: "GG $22 freeze (1st)",
        players: 1500,
        buyIn: 20,
        rake: 0.1,
        roi: 0.1,
        payoutStructure: "mtt-gg",
        guarantee: 25_000,
        count: 30,
      },
      {
        id: "romeo-fr22-2",
        label: "GG $22 freeze (re-1)",
        players: 1500,
        buyIn: 20,
        rake: 0.1,
        roi: 0.05,
        payoutStructure: "mtt-gg",
        guarantee: 25_000,
        count: 15,
      },
      {
        id: "romeo-fr22-3",
        label: "GG $22 freeze (re-2)",
        players: 1500,
        buyIn: 20,
        rake: 0.1,
        roi: 0.025,
        payoutStructure: "mtt-gg",
        guarantee: 25_000,
        count: 7,
      },
      {
        id: "romeo-fr55-1",
        label: "PS Big $55 (1st)",
        players: 1800,
        buyIn: 50,
        rake: 0.09,
        roi: 0.08,
        payoutStructure: "mtt-pokerstars",
        guarantee: 75_000,
        count: 30,
      },
      {
        id: "romeo-fr55-2",
        label: "PS Big $55 (re-1)",
        players: 1800,
        buyIn: 50,
        rake: 0.09,
        roi: 0.04,
        payoutStructure: "mtt-pokerstars",
        guarantee: 75_000,
        count: 15,
      },
      {
        id: "romeo-fr55-3",
        label: "PS Big $55 (re-2)",
        players: 1800,
        buyIn: 50,
        rake: 0.09,
        roi: 0.02,
        payoutStructure: "mtt-pokerstars",
        guarantee: 75_000,
        count: 7,
      },
      // ---- Named events, 1 shot each ----
      {
        id: "romeo-named-thrill",
        label: "PS Thursday Thrill $109",
        players: 1500,
        buyIn: 100,
        rake: 0.09,
        roi: 0.07,
        payoutStructure: "mtt-pokerstars",
        guarantee: 150_000,
        count: 1,
      },
      {
        id: "romeo-named-bhmain",
        label: "GG BH Main $210",
        players: 2000,
        buyIn: 200,
        rake: 0.05,
        roi: 0.05,
        payoutStructure: "mtt-gg-bounty",
        bountyFraction: 0.5,
        guarantee: 400_000,
        count: 1,
      },
    ],
    controls: {
      ...BASE_CONTROLS,
      scheduleRepeats: 50,
      samples: 8_000,
      bankroll: 15_000,
      finishModelId: "power-law",
    },
  },
];

export function findScenario(id: string): DemoScenario | undefined {
  return SCENARIOS.find((s) => s.id === id);
}
