import type { ControlsState } from "@/components/ControlsPanel";
import type { TournamentRow } from "./sim/types";
import type { DictKey } from "./i18n/dict";

export interface DemoScenario {
  id: string;
  labelKey: DictKey;
  description: string;
  schedule: TournamentRow[];
  controls: ControlsState;
}

const BASE_CONTROLS: ControlsState = {
  scheduleRepeats: 200,
  samples: 10_000,
  bankroll: 0,
  seed: 42,
  finishModelId: "power-law",
  alphaOverride: null,
  compareWithPrimedope: true,
};

export const SCENARIOS: DemoScenario[] = [
  {
    id: "nano-grinder",
    labelKey: "demo.nanoGrinder",
    description: "Freeroll-style grinder: 500-field $1 MTTs + some $2 knockouts",
    schedule: [
      {
        id: "nano-1",
        label: "$1.10 rebuy 500",
        players: 500,
        buyIn: 1,
        rake: 0.1,
        roi: 0.15,
        payoutStructure: "mtt-standard",
        count: 4,
      },
      {
        id: "nano-2",
        label: "$2.20 KO 300",
        players: 300,
        buyIn: 2,
        rake: 0.1,
        roi: 0.18,
        payoutStructure: "mtt-top-heavy",
        count: 2,
      },
    ],
    controls: {
      ...BASE_CONTROLS,
      scheduleRepeats: 300,
      bankroll: 100,
    },
  },
  {
    id: "micro-grinder",
    labelKey: "demo.microGrinder",
    description: "Bread-and-butter $5–$11 MTT grinder with a Sunday anchor",
    schedule: [
      {
        id: "micro-1",
        label: "$5.50 daily",
        players: 800,
        buyIn: 5,
        rake: 0.1,
        roi: 0.12,
        payoutStructure: "mtt-standard",
        count: 3,
      },
      {
        id: "micro-2",
        label: "$11 turbo 500",
        players: 500,
        buyIn: 10,
        rake: 0.1,
        roi: 0.15,
        payoutStructure: "mtt-pokerstars",
        count: 2,
      },
      {
        id: "micro-3",
        label: "Sunday $22 2k",
        players: 2000,
        buyIn: 20,
        rake: 0.1,
        roi: 0.2,
        payoutStructure: "mtt-pokerstars",
        count: 1,
      },
    ],
    controls: {
      ...BASE_CONTROLS,
      scheduleRepeats: 250,
      bankroll: 500,
    },
  },
  {
    id: "mid-grinder",
    labelKey: "demo.midGrinder",
    description: "Mid-stakes reg: $55–$215, conservative 15% ROI",
    schedule: [
      {
        id: "mid-1",
        label: "$55 nightly 600",
        players: 600,
        buyIn: 50,
        rake: 0.1,
        roi: 0.12,
        payoutStructure: "mtt-pokerstars",
        count: 3,
      },
      {
        id: "mid-2",
        label: "$109 2k",
        players: 2000,
        buyIn: 100,
        rake: 0.09,
        roi: 0.15,
        payoutStructure: "mtt-pokerstars",
        count: 1,
      },
      {
        id: "mid-3",
        label: "$215 800",
        players: 800,
        buyIn: 200,
        rake: 0.075,
        roi: 0.1,
        payoutStructure: "mtt-top-heavy",
        count: 1,
      },
    ],
    controls: {
      ...BASE_CONTROLS,
      scheduleRepeats: 200,
      bankroll: 5000,
      finishModelId: "stretched-exp",
    },
  },
  {
    id: "hyper-night",
    labelKey: "demo.hyperNight",
    description: "Hyper-turbo SNG + HU night — high-variance short stuff",
    schedule: [
      {
        id: "hyper-1",
        label: "$10 hyper 6-max",
        players: 6,
        buyIn: 10,
        rake: 0.05,
        roi: 0.05,
        payoutStructure: "sng-65-35",
        count: 30,
      },
      {
        id: "hyper-2",
        label: "$25 HU",
        players: 2,
        buyIn: 25,
        rake: 0.04,
        roi: 0.08,
        payoutStructure: "winner-takes-all",
        count: 15,
      },
    ],
    controls: {
      ...BASE_CONTROLS,
      scheduleRepeats: 100,
      bankroll: 500,
      finishModelId: "linear-skill",
    },
  },
  {
    id: "spin-hunter",
    labelKey: "demo.spinHunter",
    description:
      "Extreme variance: tiny-field hyper SNGs + bounty turbos. 90% of sessions are below EV, but the tail is fat.",
    schedule: [
      {
        id: "spin-1",
        label: "$5 spin 3-max",
        players: 3,
        buyIn: 5,
        rake: 0.07,
        roi: 0.03,
        payoutStructure: "winner-takes-all",
        count: 60,
      },
      {
        id: "spin-2",
        label: "$10 hyper KO 6-max",
        players: 6,
        buyIn: 10,
        rake: 0.05,
        roi: 0.06,
        payoutStructure: "sng-65-35",
        bountyFraction: 0.5,
        count: 25,
      },
      {
        id: "spin-3",
        label: "$25 PKO mini-MTT",
        players: 90,
        buyIn: 25,
        rake: 0.08,
        roi: 0.08,
        payoutStructure: "mtt-gg-bounty",
        bountyFraction: 0.5,
        count: 6,
      },
    ],
    controls: {
      ...BASE_CONTROLS,
      scheduleRepeats: 150,
      samples: 12_000,
      bankroll: 400,
      finishModelId: "linear-skill",
      compareWithPrimedope: true,
    },
  },
  {
    id: "big-field-reg",
    labelKey: "demo.bigFieldReg",
    description:
      "Big-field MTT volume grinder: 3k+ entry pools, thin ROI, relentless count. Shows off fat-tail drawdowns.",
    schedule: [
      {
        id: "bf-1",
        label: "$11 3k rebuy",
        players: 3000,
        buyIn: 10,
        rake: 0.1,
        roi: 0.08,
        payoutStructure: "mtt-pokerstars",
        count: 4,
        maxEntries: 3,
        reentryRate: 0.5,
      },
      {
        id: "bf-2",
        label: "$22 5k daily",
        players: 5000,
        buyIn: 20,
        rake: 0.1,
        roi: 0.1,
        payoutStructure: "mtt-pokerstars",
        count: 2,
      },
      {
        id: "bf-3",
        label: "$55 2k nightly",
        players: 2000,
        buyIn: 50,
        rake: 0.09,
        roi: 0.12,
        payoutStructure: "mtt-top-heavy",
        count: 1,
      },
    ],
    controls: {
      ...BASE_CONTROLS,
      scheduleRepeats: 250,
      samples: 12_000,
      bankroll: 2000,
      finishModelId: "stretched-exp",
      compareWithPrimedope: true,
    },
  },
  {
    id: "satellite-feeder",
    labelKey: "demo.satelliteFeeder",
    description:
      "Satellite-heavy qualifier chain: cheap feeders into a target tourney. Field sizes vary wildly — PrimeDope can't model this.",
    schedule: [
      {
        id: "sat-1",
        label: "$2 sat to $22",
        players: 100,
        buyIn: 2,
        rake: 0.1,
        roi: 0.2,
        payoutStructure: "sng-50-30-20",
        count: 15,
        fieldVariability: { kind: "uniform", min: 20, max: 250, buckets: 6 },
      },
      {
        id: "sat-2",
        label: "$11 sat to $109",
        players: 200,
        buyIn: 10,
        rake: 0.08,
        roi: 0.18,
        payoutStructure: "mtt-flat",
        count: 8,
        fieldVariability: { kind: "uniform", min: 60, max: 450, buckets: 6 },
      },
      {
        id: "sat-3",
        label: "$109 target MTT",
        players: 1500,
        buyIn: 100,
        rake: 0.08,
        roi: 0.15,
        payoutStructure: "mtt-pokerstars",
        guarantee: 200_000,
        count: 1,
      },
    ],
    controls: {
      ...BASE_CONTROLS,
      scheduleRepeats: 100,
      samples: 10_000,
      bankroll: 1500,
      finishModelId: "power-law",
      compareWithPrimedope: true,
    },
  },
  {
    id: "sunday-majors",
    labelKey: "demo.sundayMajors",
    description: "Sunday Million + Warm-up + Bounty Builder",
    schedule: [
      {
        id: "sun-1",
        label: "Sunday Million",
        players: 8000,
        buyIn: 100,
        rake: 0.09,
        roi: 0.25,
        payoutStructure: "mtt-sunday-million",
        guarantee: 1_000_000,
        count: 1,
      },
      {
        id: "sun-2",
        label: "Warm-up $215",
        players: 1500,
        buyIn: 200,
        rake: 0.075,
        roi: 0.2,
        payoutStructure: "mtt-pokerstars",
        count: 1,
      },
      {
        id: "sun-3",
        label: "GG Bounty $100",
        players: 2500,
        buyIn: 100,
        rake: 0.08,
        roi: 0.18,
        payoutStructure: "mtt-gg-bounty",
        count: 1,
      },
    ],
    controls: {
      ...BASE_CONTROLS,
      scheduleRepeats: 52,
      samples: 15_000,
      bankroll: 20_000,
      finishModelId: "stretched-exp",
    },
  },
];

export function findScenario(id: string): DemoScenario | undefined {
  return SCENARIOS.find((s) => s.id === id);
}
